version: "3.8"
services:
  perizia_web_server_app:
    image: perizia_web_server_app:latest
    restart: always
    depends_on:
      - db
      - adminer
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        buildno: 1
    volumes:
      - ./ServerApp/img/:/root/ServerApp/img/
    ports:
      - 3010:3000
    networks:
      - internal-network
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - internal-network
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - internal-network

networks:
  internal-network:
