version: '3.8'
services:
  db:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example1
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - internal-network
    ports:
      - target: 5432
        published: 5434
  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8081:8080
    networks:
      - internal-network

networks:
  internal-network:
