version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - internal-network
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - internal-network

networks:
  internal-network:
