version: '3.8'
services:
  perizia_web_server_app:
    #image: perizia_web_server_app:latest
    restart: unless-stopped
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        buildno: 1
    volumes:
      - /root/perizia/ServerApp/img/:/root/ServerApp/img
    ports:
      - 3010:3000
    networks:
      - internal-network
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_PORT: 5432
    networks:
      - internal-network
    ports:
      - 5434:5432
    volumes:
      -  /root/perizia/postgresql/data//:/var/lib/postgresql/data

volumes:
  db-data:
networks:
  internal-network:
