version: "3.8"
services:
  perizia_server_app:
    image: perizia_server_app:1.0.0
    restart: always
    depends_on:
      - db
      - adminer
    build:
      context: ./
      dockerfile: DockerfileServerApp
      args:
        buildno: 1
    environment:
      PGUSER: postgres
      PGHOST: db
      PGPASSWORD: example
      PGDATABASE: postgres
      PGPORT: 5432

    ports:
      - 3001:3001
    networks:
      - internal-network
  perizia_web_app:
    stdin_open: true
    image: perizia_web_app:1.0.0
    restart: always
    depends_on:
      - db
      - adminer
      - perizia_server_app
    build:
      context: ./
      dockerfile: DockerfileWebApp
      args:
        buildno: 1
    # environment:
    #   PGUSER: postgres
    #   PGHOST: db
    #   PGPASSWORD: example
    #   PGDATABASE: postgres
    #   PGPORT: 5432
    volumes:
      - ./WebApp/public:/WebApp/public
      - ./WebApp/src:/WebApp/src
    ports:
      - 3010:3000
    networks:
      - internal-network
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - internal-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - internal-network

networks:
  internal-network:
